title: Maya B. Mathur
description: Associate Professor at Stanford University
url: "https://www.mayamathur.com"

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from the site build
exclude:
  - README.md
  - README_DEPLOY.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
